# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Mod Properties
version=2.0.3+1.21.1
maven_group=de.dafuqs
mod_id=additionalentityattributes

# Common
minecraft_version=1.21.1
neoform_version=1.21-20240613.152323
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21
parchment_version=2024.07.28

# Fabric
fabric_api_version=0.106.0+1.21.1
fabric_loader_version=0.16.7
fabric_minecraft_version_range=>=1.21.1

# NeoForge
neoforge_version=21.1.72
neoforge_version_range=[21.1,)
neoforge_minecraft_version_range=[1.21.1,)
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
