# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Mod Properties
version=2.1.1+1.21.7
maven_group=de.dafuqs
mod_id=additionalentityattributes

# Common
minecraft_version=1.21.7
# https://github.com/neoforged/NeoForm
# https://maven.neoforged.net/releases/net/neoforged/neoform/
neoform_version=1.21.7-20250711.194848
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.6
parchment_version=2025.06.29

# Fabric
fabric_api_version=0.129.0+1.21.7
fabric_loader_version=0.16.14
fabric_minecraft_version_range=>=1.21.6

# NeoForge
# https://neoforged.net/
neoforge_version=21.7.20-beta
neoforge_version_range=[21.6,)
neoforge_minecraft_version_range=[1.21.6,)
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
