# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Mod Properties
version=2.2.1+1.21.8
maven_group=de.dafuqs
mod_id=additionalentityattributes

# Common
minecraft_version=1.21.8
# https://github.com/neoforged/NeoForm
# https://maven.neoforged.net/releases/net/neoforged/neoform/
neoform_version=1.21.8-20250717.133445
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.8
parchment_version=2025.07.20

# Fabric
fabric_api_version=0.132.0+1.21.8
fabric_loader_version=0.17.2
fabric_minecraft_version_range=>=1.21.8

# NeoForge
# https://neoforged.net/
neoforge_version=21.8.36
neoforge_version_range=[21.8.36,]
neoforge_minecraft_version_range=[1.21.8,)
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
